{ lib }:
let
  shellAliases = {
    gadd = "git add .";
    gcm = "git commit --message";
    k = "kubectl";
    p = "pulumi";
    pd = "pulumi destroy";
    pp = "pulumi preview";
    ppd = "pulumi preview --diff";
    pup = "pulumi up --yes --skip-preview";
  };

  aliasLines = aliases:
    lib.concatStringsSep "\n" (
      lib.mapAttrsToList (name: value: "alias ${name}=${lib.escapeShellArg value}") aliases
    );
in
{
  inherit shellAliases;

  mkPortableBashRc =
    {
      aliases ? { },
      includeLocalBin ? true,
    }:
    ''
      # shellcheck shell=bash
      # Generated by Nix. Source this file or start bash with `--rcfile`.

      if [[ -n "${UNSTOPPABLEMANGO_PORTABLE_BASHRC_SOURCED:-}" ]]; then
        return 0
      fi
      export UNSTOPPABLEMANGO_PORTABLE_BASHRC_SOURCED=1

      ${lib.optionalString includeLocalBin ''
        case ":$PATH:" in
          *":$HOME/.local/bin:"*) ;;
          *) export PATH="$HOME/.local/bin:$PATH" ;;
        esac
      ''}

      shopt -s histappend
      HISTCONTROL=ignoreboth
      HISTSIZE=10000
      HISTFILESIZE=10000
      HISTFILE="${HISTFILE:-$HOME/.bash_history}"

      if command -v crc >/dev/null 2>&1; then
        eval "$(crc podman-env)"
      fi

      export PATH="''${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

      if command -v fnm >/dev/null 2>&1; then
        eval "$(fnm env --use-on-cd --shell bash)"
      fi

      if command -v opam >/dev/null 2>&1; then
        eval "$(opam env --shell=bash)"
      fi

      if command -v direnv >/dev/null 2>&1; then
        eval "$(direnv hook bash)"
      fi

      if tty >/dev/null 2>&1; then
        export GPG_TTY="$(tty)"
      fi

      if command -v gpg-connect-agent >/dev/null 2>&1; then
        gpg-connect-agent --quiet updatestartuptty /bye > /dev/null
      fi

      ${aliasLines (shellAliases // aliases)}
    '';
}
